# fly.toml app configuration file generated for christi-capstone-backend on 2024-01-28T22:11:45-05:00
#
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
internal_port = 3000
protocol = "tcp"

  [[services.ports]]
  handlers = ["http"]
  port = 80

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[services.tcp_checks]]
interval = 10000
timeout = 2000

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024